### ISSUE TITLE
Modem Examples doesn't work

### ISSUE THREAD

**Issue by CsFreiber** [microchip-pic-avr-solutions/avr-iot-cellular-arduino-library#7]
Hello Microchip,

I have issues with the example scripts which are using the Sequans modem. After compiling, the AVR-IoT-Cellular is having already a problem in the void setup() function. The first method (for example SequansController.begin() in debug_modem.ino or Log.info() in http_get_time.ino) executes but then the microcontroller crashes and restart itself in a loop.
I am using the Arduino IDE v1.8.19 and VS Code and I have the same issue with both IDEs.
The on-boarding / sandbox firmware is working fine (Heartbeat is beeing sent) and the SIM card is active and online (can be checked by Truephone). Also the example script power_print_voltage.ino and my code is working, however I haven't used there the modem yet.

Do you have any suggestions for solving this issue?

Best regards
C.F.

**Comment by M65649** [comment]
Hello,

We've found the root cause of this. This is due to the new interrupt system in DxCore 1.5 and an undefined ISR. We've submitted a PR here: https://github.com/SpenceKonde/DxCore/pull/388, which probably will be merged in soon. In the mean time, to alleviate the problem, in the Arduino IDE go to tools -> attachInterrupt() version -> Old version.

**Comment by CsFreiber** [comment]
Hello,

thank you for your help. Indeed the new commit from SpenceKonde fixed this problem.
